# Starts only postgres db
services:
  postgres:
    container_name: cd_008_postgres_standalone
    build:
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_pwd
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=user_db
