# Docker Compose to instantiate all services together
services:
  # Postgres Container
  postgres:
    container_name: cd_008_postgres
    build:
      dockerfile: postgres.Dockerfile
      context: 1_rdbms/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres_pwd
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=user_db
  # Mongo Container
  mongo:
    image: mongo:7.0.4-jammy
    restart: always
    container_name: cd_008_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pwd
      MONGO_INITDB_DATABASE: users
    ports:
      - 27017:27017
    volumes:
      - ./2_mongo_db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro