spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://backend_database:5432/backend_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver