# Starts ONLY mongodb
services:
  mongo:
    image: mongo:7.0.4-jammy
    restart: always
    container_name: cd_008_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pwd
      MONGO_INITDB_DATABASE: users
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro