version: '3.9'

services:
  mongo:
    image: mongo:7.0.4-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pwd
      MONGO_INITDB_DATABASE: user_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_pwd
      ME_CONFIG_MONGODB_URL: mongodb://mongo_user:mongo_pwd@mongo:27017/
